apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mimir-monitoring

resources:
  - prometheus-deployment.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - alertmanager-config.yaml
  - grafana-deployment.yaml
  - grafana-dashboards-mimir.yaml
  - grafana-dashboards-infrastructure.yaml
  - custom-metrics-adapter.yaml

configMapGenerator:
  - name: monitoring-version
    literals:
      - VERSION=1.0.0
      - PROMETHEUS_VERSION=v2.45.0
      - GRAFANA_VERSION=10.0.3
      - ALERTMANAGER_VERSION=v0.26.0

commonLabels:
  app.kubernetes.io/part-of: mimir
  app.kubernetes.io/managed-by: kustomize

# Patches for production
patches:
  - target:
      kind: PersistentVolumeClaim
      name: prometheus-data
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 200Gi
  
  - target:
      kind: PersistentVolumeClaim
      name: grafana-storage
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 20Gi