version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16-latest
    container_name: mimir_timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_DB: mimir_analytics
      POSTGRES_USER: mimir_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mimir_dev_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
      # Enable TimescaleDB extensions
      TS_TUNE_MEMORY: 4GB
      TS_TUNE_NUM_CPUS: 4
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./scripts/timescale/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mimir_user -d mimir_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_preload_libraries=timescaledb
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200

  postgres:
    image: postgres:16-alpine
    container_name: mimir_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mimir_news
      POSTGRES_USER: mimir_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mimir_dev_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mimir_user -d mimir_news"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    container_name: mimir_pgbouncer
    restart: unless-stopped
    environment:
      DATABASES_HOST: postgres
      DATABASES_PORT: 5432
      DATABASES_USER: mimir_user
      DATABASES_PASSWORD: ${POSTGRES_PASSWORD:-mimir_dev_password}
      DATABASES_DBNAME: mimir_news
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 25
    ports:
      - "6432:5432"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config/pgbouncer:/etc/pgbouncer

  redis:
    image: redis:7-alpine
    container_name: mimir_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: mimir_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      - postgres
      - timescaledb

volumes:
  postgres_data:
  timescale_data:
  redis_data:

networks:
  default:
    name: mimir_network