apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mimir-tracing

resources:
  - jaeger-deployment.yaml
  - jaeger-config.yaml

configMapGenerator:
  - name: tracing-version
    literals:
      - VERSION=1.0.0
      - JAEGER_VERSION=1.50
      - OTEL_VERSION=1.20.0

commonLabels:
  app.kubernetes.io/part-of: mimir
  app.kubernetes.io/managed-by: kustomize

# Patches for production
patches:
  - target:
      kind: Deployment
      name: jaeger-collector
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1Gi
  
  - target:
      kind: Deployment
      name: jaeger-query
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3