apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: mimir-pod-failure
  namespace: mimir-production
spec:
  action: pod-failure
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - mimir-production
    labelSelectors:
      app: mimir-web
  scheduler:
    cron: "@every 24h"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: mimir-network-delay
  namespace: mimir-production
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - mimir-production
    labelSelectors:
      app: mimir-api
  delay:
    latency: "100ms"
    correlation: "100"
    jitter: "0ms"
  duration: "120s"
  scheduler:
    cron: "0 2 * * 1"  # Every Monday at 2 AM

---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mimir-cpu-stress
  namespace: mimir-production
spec:
  mode: one
  selector:
    namespaces:
      - mimir-production
    labelSelectors:
      app: mimir-worker
  duration: "300s"
  stressors:
    cpu:
      workers: 1
      load: 80
  scheduler:
    cron: "0 3 * * 2"  # Every Tuesday at 3 AM

---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: mimir-disk-stress
  namespace: mimir-production
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - mimir-production
    labelSelectors:
      app: postgres
  volumePath: /var/lib/postgresql/data
  path: "**/*"
  delay: "100ms"
  percent: 50
  duration: "180s"
  scheduler:
    cron: "0 4 * * 3"  # Every Wednesday at 4 AM

---
# Chaos experiment workflow
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: mimir-chaos-testing
  namespace: mimir-production
spec:
  entry: sequential-chaos
  templates:
    - name: sequential-chaos
      templateType: Serial
      deadline: "20m"
      children:
        - pod-chaos-test
        - network-chaos-test
        - stress-chaos-test
        
    - name: pod-chaos-test
      templateType: PodChaos
      deadline: "5m"
      podChaos:
        action: pod-kill
        mode: one
        selector:
          namespaces:
            - mimir-production
          labelSelectors:
            app: mimir-web
            
    - name: network-chaos-test
      templateType: NetworkChaos
      deadline: "5m"
      networkChaos:
        action: partition
        mode: one
        selector:
          namespaces:
            - mimir-production
          labelSelectors:
            app: mimir-api
        direction: to
        target:
          mode: one
          selector:
            namespaces:
              - mimir-production
            labelSelectors:
              app: postgres
              
    - name: stress-chaos-test
      templateType: StressChaos
      deadline: "10m"
      stressChaos:
        mode: one
        selector:
          namespaces:
            - mimir-production
          labelSelectors:
            app: mimir-worker
        stressors:
          memory:
            workers: 1
            size: "512MB"