//! HTML email templates for AirPulse digest notifications.

/// Render a digest markdown body into a full HTML email with inline CSS,
/// amber header bar, AirPulse branding, and footer.
pub fn render_digest_html(markdown: &str, week: &str) -> String {
    // Convert basic markdown to HTML (simple conversion for digest content)
    let body_html = markdown_to_html(markdown);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AirPulse Weekly Intelligence Digest — {week}</title>
    <style>
        body {{
            margin: 0;
            padding: 0;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 680px;
            margin: 0 auto;
            background-color: #ffffff;
        }}
        .header {{
            background-color: #F59E0B;
            padding: 24px 32px;
            color: #ffffff;
        }}
        .header h1 {{
            margin: 0;
            font-size: 24px;
            font-weight: 700;
        }}
        .header .subtitle {{
            margin: 4px 0 0;
            font-size: 14px;
            opacity: 0.9;
        }}
        .content {{
            padding: 32px;
        }}
        .content h2 {{
            color: #1F2937;
            border-bottom: 2px solid #F59E0B;
            padding-bottom: 8px;
            margin-top: 28px;
        }}
        .content h3 {{
            color: #374151;
            margin-top: 20px;
        }}
        .content p {{
            margin: 12px 0;
        }}
        .content ul {{
            padding-left: 24px;
        }}
        .content li {{
            margin: 6px 0;
        }}
        .footer {{
            background-color: #1F2937;
            color: #9CA3AF;
            padding: 20px 32px;
            font-size: 12px;
            text-align: center;
        }}
        .footer a {{
            color: #F59E0B;
            text-decoration: none;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>AirPulse Intelligence Digest</h1>
            <div class="subtitle">Week of {week} | Mediagenix Hive Department</div>
        </div>
        <div class="content">
            {body_html}
        </div>
        <div class="footer">
            <p>Generated by AirPulse — Broadcast Intelligence Module</p>
            <p>Mediagenix NV | <a href="https://mediagenix.tv">mediagenix.tv</a></p>
            <p>This is an automated intelligence digest. Do not reply to this email.</p>
        </div>
    </div>
</body>
</html>"#,
        week = week,
        body_html = body_html,
    )
}

/// Simple markdown-to-HTML converter for digest content.
/// Handles headers (##, ###), bold (**), italic (*), bullet lists, and paragraphs.
fn markdown_to_html(markdown: &str) -> String {
    let mut html = String::new();
    let mut in_list = false;

    for line in markdown.lines() {
        let trimmed = line.trim();

        if trimmed.is_empty() {
            if in_list {
                html.push_str("</ul>\n");
                in_list = false;
            }
            continue;
        }

        // Headers
        if let Some(rest) = trimmed.strip_prefix("### ") {
            if in_list {
                html.push_str("</ul>\n");
                in_list = false;
            }
            html.push_str(&format!("<h3>{}</h3>\n", escape_html(rest)));
        } else if let Some(rest) = trimmed.strip_prefix("## ") {
            if in_list {
                html.push_str("</ul>\n");
                in_list = false;
            }
            html.push_str(&format!("<h2>{}</h2>\n", escape_html(rest)));
        } else if let Some(rest) = trimmed.strip_prefix("# ") {
            if in_list {
                html.push_str("</ul>\n");
                in_list = false;
            }
            html.push_str(&format!("<h1>{}</h1>\n", escape_html(rest)));
        }
        // Bullet list items
        else if let Some(rest) = trimmed.strip_prefix("- ").or_else(|| trimmed.strip_prefix("* "))
        {
            if !in_list {
                html.push_str("<ul>\n");
                in_list = true;
            }
            html.push_str(&format!("<li>{}</li>\n", inline_format(rest)));
        }
        // Regular paragraph
        else {
            if in_list {
                html.push_str("</ul>\n");
                in_list = false;
            }
            html.push_str(&format!("<p>{}</p>\n", inline_format(trimmed)));
        }
    }

    if in_list {
        html.push_str("</ul>\n");
    }

    html
}

/// Apply inline formatting: **bold** and *italic*.
fn inline_format(text: &str) -> String {
    let escaped = escape_html(text);

    // Simple bold replacement: pairs of ** become <strong>...</strong>
    let mut result = String::new();
    let mut in_bold = false;
    let parts: Vec<&str> = escaped.split("**").collect();
    for (i, part) in parts.iter().enumerate() {
        result.push_str(part);
        if i < parts.len() - 1 {
            if in_bold {
                result.push_str("</strong>");
            } else {
                result.push_str("<strong>");
            }
            in_bold = !in_bold;
        }
    }

    result
}

/// Escape HTML special characters.
fn escape_html(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_html_has_header() {
        let html = render_digest_html("## Test Section\nSome content.", "2026-W13");
        assert!(html.contains("AirPulse Intelligence Digest"));
        assert!(html.contains("class=\"header\""));
        assert!(html.contains("#F59E0B")); // amber color
        assert!(html.contains("2026-W13"));
    }

    #[test]
    fn test_html_has_footer() {
        let html = render_digest_html("Content here.", "2026-W13");
        assert!(html.contains("class=\"footer\""));
        assert!(html.contains("Mediagenix"));
        assert!(html.contains("mediagenix.tv"));
        assert!(html.contains("Do not reply"));
    }

    #[test]
    fn test_html_contains_content() {
        let html = render_digest_html("Important signal about AWS.", "2026-W13");
        assert!(html.contains("Important signal about AWS."));
    }

    #[test]
    fn test_html_escapes_special_chars() {
        let html = render_digest_html("Revenue > $1B & growing <fast>.", "2026-W13");
        assert!(html.contains("&amp;"));
        assert!(html.contains("&lt;fast&gt;"));
    }

    #[test]
    fn test_html_renders_headers() {
        let html = render_digest_html("## Shift Signals\n### AI Trends", "2026-W13");
        assert!(html.contains("<h2>"));
        assert!(html.contains("<h3>"));
    }

    #[test]
    fn test_html_renders_list() {
        let html = render_digest_html("- Item one\n- Item two", "2026-W13");
        assert!(html.contains("<ul>"));
        assert!(html.contains("<li>"));
        assert!(html.contains("</ul>"));
    }
}
