apiVersion: v1
kind: Service
metadata:
  name: mimir-analytics-service
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-analytics
    app.kubernetes.io/component: analytics
    app.kubernetes.io/part-of: mimir
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: mimir-analytics
    app.kubernetes.io/component: analytics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-analytics
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-analytics
    app.kubernetes.io/component: analytics
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir-analytics
      app.kubernetes.io/component: analytics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir-analytics
        app.kubernetes.io/component: analytics
        app.kubernetes.io/part-of: mimir
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: mimir-analytics
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      initContainers:
      - name: wait-for-dependencies
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          until nc -z postgres-service 5432 && nc -z redis-service 6379; do
            echo "Waiting for dependencies..."
            sleep 2
          done
          echo "Dependencies are ready"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      containers:
      - name: mimir-analytics
        image: {{ .Values.image.registry }}/mimir:analytics-{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - python
        - analytics_manager.py
        - dashboard
        - --port=5001
        - --host=0.0.0.0
        ports:
        - containerPort: 5001
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        envFrom:
        - configMapRef:
            name: mimir-config
        - secretRef:
            name: mimir-secrets
        env:
        - name: SERVICE_TYPE
          value: "analytics"
        - name: MPLBACKEND
          value: "Agg"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
            httpHeaders:
            - name: User-Agent
              value: Kubernetes-Health-Check
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
            httpHeaders:
            - name: User-Agent
              value: Kubernetes-Health-Check
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
          successThreshold: 1
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
        - name: reports
          mountPath: /app/reports
        - name: matplotlib-config
          mountPath: /home/mimir/.config/matplotlib
        - name: cache
          mountPath: /home/mimir/.cache
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      - name: reports
        emptyDir:
          sizeLimit: 10Gi
      - name: matplotlib-config
        emptyDir: {}
      - name: cache
        emptyDir:
          sizeLimit: 5Gi
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: mimir-analytics
            app.kubernetes.io/component: analytics
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - mimir-analytics
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - memory-optimized
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir-analytics
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-analytics
    app.kubernetes.io/component: analytics
    app.kubernetes.io/part-of: mimir
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-analytics-pdb
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-analytics
    app.kubernetes.io/component: analytics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir-analytics
      app.kubernetes.io/component: analytics