# This is a template for Kubernetes secrets
# DO NOT commit actual secret values to version control
# Use a secrets management tool like Sealed Secrets, SOPS, or HashiCorp Vault
apiVersion: v1
kind: Secret
metadata:
  name: mimir-secrets
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_USER: "mimir_user"
  POSTGRES_PASSWORD: "CHANGE_THIS_STRONG_PASSWORD_123"
  DATABASE_URL: "postgresql://mimir_user:CHANGE_THIS_STRONG_PASSWORD_123@postgres-service:5432/mimir_news"
  
  # Redis Credentials
  REDIS_PASSWORD: "CHANGE_THIS_REDIS_PASSWORD_456"
  REDIS_URL: "redis://:CHANGE_THIS_REDIS_PASSWORD_456@redis-service:6379/0"
  
  # Celery Configuration
  CELERY_BROKER_URL: "redis://:CHANGE_THIS_REDIS_PASSWORD_456@redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://:CHANGE_THIS_REDIS_PASSWORD_456@redis-service:6379/0"
  
  # Application Secrets
  SECRET_KEY: "CHANGE_THIS_TO_RANDOM_64_CHAR_STRING"
  JWT_SECRET_KEY: "CHANGE_THIS_TO_ANOTHER_RANDOM_64_CHAR_STRING"
  ENCRYPTION_KEY: "CHANGE_THIS_TO_32_CHAR_ENCRYPTION_KEY"
  
  # API Keys
  ADMIN_API_KEY: "CHANGE_THIS_ADMIN_API_KEY"
  MONITORING_API_KEY: "CHANGE_THIS_MONITORING_API_KEY"
  
  # External Services
  SMTP_PASSWORD: "CHANGE_THIS_SMTP_PASSWORD"
  S3_ACCESS_KEY: "CHANGE_THIS_S3_ACCESS_KEY"
  S3_SECRET_KEY: "CHANGE_THIS_S3_SECRET_KEY"
  
  # OAuth/OIDC
  OAUTH_CLIENT_SECRET: "CHANGE_THIS_OAUTH_CLIENT_SECRET"
  
  # Webhook Secrets
  GITHUB_WEBHOOK_SECRET: "CHANGE_THIS_GITHUB_WEBHOOK_SECRET"
  SLACK_WEBHOOK_SECRET: "CHANGE_THIS_SLACK_WEBHOOK_SECRET"
---
apiVersion: v1
kind: Secret
metadata:
  name: mimir-tls
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Generate with: kubectl create secret tls mimir-tls --cert=tls.crt --key=tls.key --dry-run=client -o yaml
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLiBZT1VSIENFUlRJRklDQVRFIEhFUkUgLi4uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLiBZT1VSIFBSSVZBVEUgS0VZIEhFUkUgLi4uCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=