apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mimir-staging

resources:
  - ../../base
  - ../../argocd/hooks

images:
  - name: mimir
    newTag: latest
  - name: mimir-api
    newTag: latest
  - name: mimir-analytics
    newTag: latest
  - name: mimir-worker
    newTag: latest

patchesStrategicMerge:
  - patches/staging-config.yaml
  - patches/staging-resources.yaml

configMapGenerator:
  - name: mimir-config
    files:
      - config/staging.env
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: staging-secrets
    envs:
      - secrets/staging.env
    options:
      disableNameSuffixHash: true

replicas:
  - name: mimir-web
    count: 2
  - name: mimir-api
    count: 2
  - name: mimir-worker
    count: 1